### ISSUE TITLE
Can the digitonic1/php7.3-nginx image dockerfile be made public?

### ISSUE THREAD

**Issue by EmielSchmeink** [richdynamix/arc#24]
As the title suggests, I don't feel comfortable using an image without the dockerfile being public, and especially because it seems to do a lot under the hood.

**Comment by richdynamix** [comment]
Hi,

As the readme suggests we have build our images from the ContinuousPipe images as we maintain these in a much faster manor. You are free to continue using the ContinuousPipe images instead of the digitonic1 image. This was changed in V3 of Arc to give us more control.

The ContinuousPipe images can be found on Quay.io as seen here. https://quay.io/repository/continuouspipe/php7.3-nginx?tab=tags
